<a href="https://colab.research.google.com/github/NSF-DARSE/YolktoFeed/blob/main/JupyterNotebook/liverHEDI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import sys

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/

In [2]:
path = "/content/drive/Shareddrives/SCIPE-DARSE/Research Software Engineers (RSE)/Abhin/Projects/Carl Schmidt"
sys.path.append(path)

In [3]:
df_base = pd.read_csv(path+"/Liver_HEIDI_complete_ensembl_symbol.csv")

In [4]:
df_base.shape

(24869, 108)

In [6]:
# finding last row with valid gene symbol
gene_list_last_index = (df_base["Gene Symbol"] == "-").idxmax()

In [115]:
#truncating till that row
df = df_base.iloc[:gene_list_last_index]
df = df.drop(columns=["Ensembl Gene ID"])
df

,Gene Symbol,1650_summed_TPM_4,1651_summed_TPM_4,1653_summed_TPM_4,1654_summed_TPM_4,1655_summed_TPM_4,1656_summed_TPM_4,1657_summed_TPM_4,1671_summed_TPM_4,1672_summed_TPM_4,...,1735_summed_TPM_20,1736_summed_TPM_20,1742_summed_TPM_20,1743_summed_TPM_20,1744_summed_TPM_20,1745_summed_TPM_20,1746_summed_TPM_20,1747_summed_TPM_20,1748_summed_TPM_20,1749_summed_TPM_20
0,ZZZ3,2.148670,4.204060,3.609380,6.677230,3.849120,7.354150,5.040800,3.031530,2.721210,...,0.970587,1.66351,1.636580,2.459220,4.893390,2.489600,3.19717,1.468440,2.091560,0.187683
1,ZYX,24.366200,32.569200,31.253900,37.847200,37.692800,56.604800,33.385700,27.918300,34.052300,...,13.140900,24.40290,25.381200,28.666700,34.741500,22.507700,29.35630,25.152600,34.865400,12.079700
2,ZXDC,2.032480,2.471470,1.543100,3.037720,1.771860,4.079810,2.900180,2.161720,2.230180,...,0.945374,1.22140,1.271560,2.263090,2.274030,1.651320,2.59244,2.715000,2.818080,0.710741
3,ZW10,4.834760,7.150830,5.563670,10.117100,5.905610,12.052000,9.869820,6.426870,5.543910,...,2.026740,3.13406,4.484710,5.776710,8.311750,4.391920,6.41727,4.316070,5.518810,1.944010
4,ZUFSP,3.170700,2.908370,2.354820,3.346660,2.564770,3.133150,4.454180,3.496990,2.421560,...,2.675900,1.74104,1.222440,3.358820,3.351070,2.998520,2.41147,1.658470,2.003540,0.645755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14460,A4GALT,0.074452,0.156464,0.029587,0.139465,0.190539,0.308782,0.056601,0.067055,0.061017,...,0.172556,0.00000,0.131267,0.230045,0.594857,0.254973,0.22188,0.201177,0.596807,0.095215
14461,A2ML4,243.909000,340.262000,289.809000,584.728000,281.682000,509.980000,664.186000,492.456000,1092.230000,...,211.638000,641.81200,604.835000,1026.430000,1004.110000,480.376000,1000.24000,778.891000,1191.370000,394.840000
14462,A2ML2,247.332000,182.951000,172.501000,183.129000,118.826000,234.194000,283.293000,169.966000,165.030000,...,130.653000,193.07000,301.891000,275.247000,395.356000,316.083000,156.38600,128.938000,186.548000,81.135700
14463,A1CF,22.040600,55.038200,26.661900,96.158400,26.078800,69.539400,111.482000,104.168000,76.200500,...,15.616700,37.06100,14.489100,36.690700,35.393500,20.619700,48.11020,28.213400,27.961700,4.667240
14464,2KTGRL,18.362800,23.623600,27.997700,25.475700,20.566000,31.371400,26.792900,27.385400,22.523600,...,19.211000,19.48700,10.104500,23.347600,30.215600,21.947100,20.14000,18.413500,10.618500,4.852390

Checks to the implemented
- Test is the all values from column 1 df.iloc[:,1:] to the right is numbers
- Test if column name follows the same pattern

In [116]:
# Adding a column for average gene expression across all days and all chikens for prelim analysis
df.insert(1, "avg_gene_expr", df.iloc[:, 1:].sum(axis=1)/(df.shape[1]-1))

In [117]:
df

,Gene Symbol,avg_gene_expr,1650_summed_TPM_4,1651_summed_TPM_4,1653_summed_TPM_4,1654_summed_TPM_4,1655_summed_TPM_4,1656_summed_TPM_4,1657_summed_TPM_4,1671_summed_TPM_4,...,1735_summed_TPM_20,1736_summed_TPM_20,1742_summed_TPM_20,1743_summed_TPM_20,1744_summed_TPM_20,1745_summed_TPM_20,1746_summed_TPM_20,1747_summed_TPM_20,1748_summed_TPM_20,1749_summed_TPM_20
0,ZZZ3,3.622199,2.148670,4.204060,3.609380,6.677230,3.849120,7.354150,5.040800,3.031530,...,0.970587,1.66351,1.636580,2.459220,4.893390,2.489600,3.19717,1.468440,2.091560,0.187683
1,ZYX,28.979918,24.366200,32.569200,31.253900,37.847200,37.692800,56.604800,33.385700,27.918300,...,13.140900,24.40290,25.381200,28.666700,34.741500,22.507700,29.35630,25.152600,34.865400,12.079700
2,ZXDC,2.306640,2.032480,2.471470,1.543100,3.037720,1.771860,4.079810,2.900180,2.161720,...,0.945374,1.22140,1.271560,2.263090,2.274030,1.651320,2.59244,2.715000,2.818080,0.710741
3,ZW10,6.449800,4.834760,7.150830,5.563670,10.117100,5.905610,12.052000,9.869820,6.426870,...,2.026740,3.13406,4.484710,5.776710,8.311750,4.391920,6.41727,4.316070,5.518810,1.944010
4,ZUFSP,3.944223,3.170700,2.908370,2.354820,3.346660,2.564770,3.133150,4.454180,3.496990,...,2.675900,1.74104,1.222440,3.358820,3.351070,2.998520,2.41147,1.658470,2.003540,0.645755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14460,A4GALT,0.295477,0.074452,0.156464,0.029587,0.139465,0.190539,0.308782,0.056601,0.067055,...,0.172556,0.00000,0.131267,0.230045,0.594857,0.254973,0.22188,0.201177,0.596807,0.095215
14461,A2ML4,663.624438,243.909000,340.262000,289.809000,584.728000,281.682000,509.980000,664.186000,492.456000,...,211.638000,641.81200,604.835000,1026.430000,1004.110000,480.376000,1000.24000,778.891000,1191.370000,394.840000
14462,A2ML2,210.725798,247.332000,182.951000,172.501000,183.129000,118.826000,234.194000,283.293000,169.966000,...,130.653000,193.07000,301.891000,275.247000,395.356000,316.083000,156.38600,128.938000,186.548000,81.135700
14463,A1CF,52.387588,22.040600,55.038200,26.661900,96.158400,26.078800,69.539400,111.482000,104.168000,...,15.616700,37.06100,14.489100,36.690700,35.393500,20.619700,48.11020,28.213400,27.961700,4.667240
14464,2KTGRL,22.548257,18.362800,23.623600,27.997700,25.475700,20.566000,31.371400,26.792900,27.385400,...,19.211000,19.48700,10.104500,23.347600,30.215600,21.947100,20.14000,18.413500,10.618500,4.852390

In [112]:
#finding average gene expression ranges
df.loc[(df.iloc[:,1] > 1e-6) & (df.iloc[:,1] < 1e-3), df.columns[0:2]]

      Gene Symbol  avg_gene_expr
353         WNT8A       0.000413
384          WEE2       0.000419
582         UTS2R       0.000345
681         UNC80       0.000698
686        UNC45B       0.000343
...           ...            ...
14092         AK7       0.000715
14101       AIM1L       0.000600
14107       AICDA       0.000964
14176      ADRA1A       0.000298
14455   AADACL4L1       0.000903

[277 rows x 2 columns]

In [102]:
df.iloc[14,1]

np.float64(0.0013308396226415094)

In [89]:
df

,Gene Symbol,avg_gene_expr,1650_summed_TPM_4,1651_summed_TPM_4,1653_summed_TPM_4,1654_summed_TPM_4,1655_summed_TPM_4,1656_summed_TPM_4,1657_summed_TPM_4,1671_summed_TPM_4,...,1735_summed_TPM_20,1736_summed_TPM_20,1742_summed_TPM_20,1743_summed_TPM_20,1744_summed_TPM_20,1745_summed_TPM_20,1746_summed_TPM_20,1747_summed_TPM_20,1748_summed_TPM_20,1749_summed_TPM_20
0,ZZZ3,3.622199,2.148670,4.204060,3.609380,6.677230,3.849120,7.354150,5.040800,3.031530,...,0.970587,1.66351,1.636580,2.459220,4.893390,2.489600,3.19717,1.468440,2.091560,0.187683
1,ZYX,28.979918,24.366200,32.569200,31.253900,37.847200,37.692800,56.604800,33.385700,27.918300,...,13.140900,24.40290,25.381200,28.666700,34.741500,22.507700,29.35630,25.152600,34.865400,12.079700
2,ZXDC,2.306640,2.032480,2.471470,1.543100,3.037720,1.771860,4.079810,2.900180,2.161720,...,0.945374,1.22140,1.271560,2.263090,2.274030,1.651320,2.59244,2.715000,2.818080,0.710741
3,ZW10,6.449800,4.834760,7.150830,5.563670,10.117100,5.905610,12.052000,9.869820,6.426870,...,2.026740,3.13406,4.484710,5.776710,8.311750,4.391920,6.41727,4.316070,5.518810,1.944010
4,ZUFSP,3.944223,3.170700,2.908370,2.354820,3.346660,2.564770,3.133150,4.454180,3.496990,...,2.675900,1.74104,1.222440,3.358820,3.351070,2.998520,2.41147,1.658470,2.003540,0.645755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14460,A4GALT,0.295477,0.074452,0.156464,0.029587,0.139465,0.190539,0.308782,0.056601,0.067055,...,0.172556,0.00000,0.131267,0.230045,0.594857,0.254973,0.22188,0.201177,0.596807,0.095215
14461,A2ML4,663.624438,243.909000,340.262000,289.809000,584.728000,281.682000,509.980000,664.186000,492.456000,...,211.638000,641.81200,604.835000,1026.430000,1004.110000,480.376000,1000.24000,778.891000,1191.370000,394.840000
14462,A2ML2,210.725798,247.332000,182.951000,172.501000,183.129000,118.826000,234.194000,283.293000,169.966000,...,130.653000,193.07000,301.891000,275.247000,395.356000,316.083000,156.38600,128.938000,186.548000,81.135700
14463,A1CF,52.387588,22.040600,55.038200,26.661900,96.158400,26.078800,69.539400,111.482000,104.168000,...,15.616700,37.06100,14.489100,36.690700,35.393500,20.619700,48.11020,28.213400,27.961700,4.667240
14464,2KTGRL,22.548257,18.362800,23.623600,27.997700,25.475700,20.566000,31.371400,26.792900,27.385400,...,19.211000,19.48700,10.104500,23.347600,30.215600,21.947100,20.14000,18.413500,10.618500,4.852390

In [49]:
#col_new_names = [name.split('_')[0] +'_' +name.split('_')[3] for name in df.columns[1:]]
#col_new_names[:5]
#df.columns = list(df.columns[:1]) + col_new_names
#df

In [50]:
chicken_tag = [tag_name.split('_')[0] for tag_name in df.columns[2:]]
list_days = list(set([int(day.split('_')[-1]) for day in df.columns[2:]]))

In [52]:
list_days.sort()
list_days

[4, 6, 8, 10, 12, 14, 16, 18, 20]

In [53]:
df_day4 = df.loc[:,["Gene Symbol"] + df.filter(regex=r"_4$").columns.tolist()]

In [54]:
df_day4

,Gene Symbol,1650_summed_TPM_4,1651_summed_TPM_4,1653_summed_TPM_4,1654_summed_TPM_4,1655_summed_TPM_4,1656_summed_TPM_4,1657_summed_TPM_4,1671_summed_TPM_4,1672_summed_TPM_4,1673_summed_TPM_4,1776_summed_TPM_4
0,ZZZ3,2.148670,4.204060,3.609380,6.677230,3.849120,7.354150,5.040800,3.031530,2.721210,3.941250,3.905400
1,ZYX,24.366200,32.569200,31.253900,37.847200,37.692800,56.604800,33.385700,27.918300,34.052300,57.311000,23.525900
2,ZXDC,2.032480,2.471470,1.543100,3.037720,1.771860,4.079810,2.900180,2.161720,2.230180,4.596810,1.855440
3,ZW10,4.834760,7.150830,5.563670,10.117100,5.905610,12.052000,9.869820,6.426870,5.543910,8.634280,6.712340
4,ZUFSP,3.170700,2.908370,2.354820,3.346660,2.564770,3.133150,4.454180,3.496990,2.421560,2.140630,2.766770
...,...,...,...,...,...,...,...,...,...,...,...,...
14460,A4GALT,0.074452,0.156464,0.029587,0.139465,0.190539,0.308782,0.056601,0.067055,0.061017,0.105077,0.153445
14461,A2ML4,243.909000,340.262000,289.809000,584.728000,281.682000,509.980000,664.186000,492.456000,1092.230000,723.640000,842.732000
14462,A2ML2,247.332000,182.951000,172.501000,183.129000,118.826000,234.194000,283.293000,169.966000,165.030000,182.840000,216.004000
14463,A1CF,22.040600,55.038200,26.661900,96.158400,26.078800,69.539400,111.482000,104.168000,76.200500,114.381000,48.011900
14464,2KTGRL,18.362800,23.623600,27.997700,25.475700,20.566000,31.371400,26.792900,27.385400,22.523600,17.135500,18.784200

In [14]:
#df_day6 = df.loc[:,["Gene Symbol"] + df.filter(regex=r"_6$").columns.tolist()]
#df_day6

In [55]:
#df